---
# handlers file for prometheus_grafana

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart Prometheus
  service:
    name: prometheus
    state: restarted

- name: Restart Grafana
  service:
    name: grafana
    state: restarted

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
